Extension { #name : #InstructionClient }

{ #category : #'*ScorchingDev' }
InstructionClient >> branchIfInstanceOf: literal distance: dist [
]

{ #category : #'*ScorchingDev' }
InstructionClient >> branchIfNotInstanceOf: literal distance: dist [
]

{ #category : #'*ScorchingDev' }
InstructionClient >> pushFullClosure: cb numCopied: num receiverOnStack: onStack ignoreOuterContext: ignoreOuterHU [
	
]
